# NetworkStorage Plugin Configuration

# The mode of operation for networks. Can be one of:
# PLAYER: Each player has their own separate network.
# GLOBAL: There is only one, server-wide network that all players share.
network-mode: PLAYER

# Maximum number of chests per network
max-chests-per-network: 100

# Maximum number of terminals per network
max-terminals-per-network: 100

# Maximum number of sender chests per network
max-sender-chests-per-network: 100

# The interval in seconds at which sender chests are checked and their contents moved to the main network.
# Lower values mean faster transfers but may increase server load.
sender-chest-transfer-interval-seconds: 5

# Auto-save interval in minutes
auto-save-interval-minutes: 5

# Enable permissions system
enable-permissions: true

# Enable the trust system (only used in PLAYER mode). If false, anyone can access any network.
enable-trust-system: true

# Langauge for Plugin-messages (de or en)
language: de

wireless-terminal-recipe:
  shape:
    - "CCC"
    - "CSC"
    - "CDC"
  ingredients:
    C: "COMPASS"
    S: "NETHER_STAR"
    D: "DIAMOND_BLOCK"
