# NetworkStorage Plugin Configuration

# Maximum number of chests per network
max-chests-per-network: 100

# Maximum number of terminals per network
max-terminals-per-network: 100

# Allow networks to span across multiple worlds
allow-cross-world-networks: false

# Auto-save interval in minutes
auto-save-interval-minutes: 5

# Enable permissions system
enable-permissions: true

# Langauge for Plugin-messages (de or en)
language: de
