name: NetworkStorage
version: 1.0
main: com.dermoha.networkstorage.NetworkStoragePlugin
api-version: 1.21
author: DerMoha
description: A networked storage system for Minecraft servers, make sharing storage easy!

commands:
  storage:
    description: Main command for NetworkStorage
    usage: /<command> [wand|info|reset|help|wireless]
    aliases: [ns, netstorage, networkstorage]
  network:
    description: Manages networks
    usage: /<command> [create|edit|rename]
    aliases: [net]

permissions:
  networkstorage.*:
    description: All NetworkStorage permissions
    default: op
    children:
      networkstorage.use: true
      networkstorage.wand: true
      networkstorage.reset: true
      networkstorage.access.all: true
      networkstorage.admin: true

  networkstorage.use:
    description: Allows basic use of storage networks
    default: true

  networkstorage.wand:
    description: Allows getting and using storage wands
    default: true

  networkstorage.wireless:
    description: Allows getting and using wireless terminals
    default: op

  networkstorage.reset:
    description: Allows resetting own storage network
    default: true

  networkstorage.access.all:
    description: Allows accessing any storage network
    default: op

  networkstorage.admin:
    description: Administrative permissions for NetworkStorage
    default: op
    children:
      networkstorage.network.create: true
      networkstorage.network.edit: true
      networkstorage.network.rename: true
      networkstorage.wireless: true

  networkstorage.network.create:
    description: Allows creating new networks
    default: op

  networkstorage.network.edit:
    description: Allows editing existing networks
    default: op

  networkstorage.network.rename:
    description: Allows renaming existing networks
    default: op
